USE timeTable;
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-CE-S1", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-CE-S1"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-CE-S2", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-CE-S2"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-CE-S3", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-CE-S3"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-CE-S4", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-CE-S4"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-CE-DSY", 15, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-CE-DSY"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-IT-S1", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-IT-S1"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-IT-S2", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-IT-S2"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-IT-S3", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-IT-S3"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-IT-S4", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-IT-S4"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYBT-IT-DSY", 15, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYBT-IT-DSY"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-T1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-T1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-T2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-T2"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-T3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-T3"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-T4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-T4"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-T5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-T5"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-T1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-T1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-T2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-T2"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-T3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-T3"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-T4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-T4"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-T5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-T5"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYMT-CE1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYMT-CE1"),(SELECT classId from class WHERE classShortName="FYMT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYMT-IS1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYMT-IS1"),(SELECT classId from class WHERE classShortName="FYMT-IS"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYMT-CE1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYMT-CE1"),(SELECT classId from class WHERE classShortName="SYMT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-CSFLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-CSFLP1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-CSFLP2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-CSFLP2"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-EC1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-EC1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-EC2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-EC2"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-NLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-NLP1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-WST1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-WST1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-WST2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-WST2"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-WST3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-WST3"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-WST4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-WST4"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-CE-WST5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-CE-WST5"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-CSFLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-CSFLP1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-CSFLP2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-CSFLP2"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-EC1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-EC1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-EC2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-EC2"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-NLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-NLP1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-WST1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-WST1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-WST2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-WST2"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-WST3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-WST3"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-WST4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-WST4"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("BT-IT-WST5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="BT-IT-WST5"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-FOSS1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-FOSS1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-CBD1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-CBD1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-CG1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-CG1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-CPES1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-CPES1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-CE-DM1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-CE-DM1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-CBD1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-CBD1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-CBD2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-CBD2"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-CG1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-CG1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-CPES1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-CPES1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-DM1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-DM1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("TYBT-IT-FOSS1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="TYBT-IT-FOSS1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
