USE timeTable;
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "AC-202", "AC-202", 100, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "AC-203", "AC-203", 100, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "AC-204", "AC-204", 100, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "SH ENTC EXTN", "SH", 80, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "DBMS Lab", "DBMSL", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "FOSS Lab-1", "FOSS1", 25 , 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "FOSS Lab-2", "FOSS2", 25 , 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Linux Lab", "LL", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Graphics and Multimedia Lab", "GML", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Digital Systems Lab", "DSL", 15, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Programming Lab", "PL", 21, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "System Software Lab", "SSL", 24, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Advanced Software Lab", "ASL", 21, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Information Security Lab", "ISL", 22, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Cognizant Lab-1", "Cogni-1", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Cognizant Lab-2", "Cogni-2", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Cognizant Lab-3", "Cogni-3", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Cognizant Lab-34", "Cogni-34", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Cognizant Lab-4", "Cogni-4", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Cognizant Lab-5", "Cogni-5", 20, 1);
INSERT INTO room(roomName, roomShortName, roomCount, snapshotId) VALUES ( "Data Mining Lab", "DML", 15, 1);
