USE timeTable;
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Fundamentals of Mathematics-II", "FM-II", 1, 3, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Electronics and Computer Workshop", "ECW", 2, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Fundamentals of Computer Programming", "FCP", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Fundamentals of Computer Programming Laboratory", "FCP-Lab", 2, 2, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Applied Biology", "AB", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Theory of Computer Science", "TCS", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Microprocessor techniques", "MPT", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Principles of Programming language", "PPL", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Data Communication", "DC", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Institute Level Open Elective Sem4", "ILOE-Sem4", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Microprocessor techniques lab", "MPT-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Principles of Programming language lab", "PPL-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Numerical Methods", "NM", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Liberal Learning Course-1", "LLC1", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Professional Science Course", "PSC", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Liberal Learning Course2", "LLC2", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "open elective 3 yr-Information Systems", "OE", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Operating Systems", "OS", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Operating Systems Lab", "OS-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Computer Aided Signal Processing", "CASP", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Software Engineering", "SE", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Computer Aided Signal Processing Laboratory", "CASP-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Software Engineering Laboratory", "SE-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Free and Open Source Software Development", "FOSS", 1, 3, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Computer Graphics", "CG", 1, 3, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Cloud and Big Data", "CBD", 1, 3, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Concurrent Programming in Embedded Systems", "CPES", 1, 3, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Data Mining", "DM", 1, 3, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Free and Open Source Software Development Laboratory", "FOSS-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Cloud and Big Data Laboratory", "CBD-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Concurrent Programming in Embedded Systems  Laboratory", "CPES-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Computer Graphics Laboratory", "CG-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Data Mining  Laboratory", "DM-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Open Elective Third Year", "OE-TY", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Language processors", "LP", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Algorithm and complexity", "AnC", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Software development process lab", "SDP-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Software development process", "SDP", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Language processors Laboratory", "LP-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Algorithm and complexity lab", "AnC-Lab", 3, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Liberal Learning Course3", "LLC3", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "open elective final yr", "OE-BTECH", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Cyber Security Forensics and Legal Perspective", "CSFLP", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Cyber Security Forensics and Legal Perspective lab", "CSFLP-Lab", 2, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "E-Commerce", "EC", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "E-Commerce lab", "EC-Lab", 2, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Natural Language Processing", "NLP", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Natural Language Processing lab", "NLP-Lab", 2, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Web Systems and Technologies", "WST", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Web Systems and Technologies  Laboratory", "WST-Lab", 2, 1, TRUE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Project Work", "Project", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Intellectual Property Rights", "IPR", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Advanced Algorithms", "AA", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Security in computing", "SIC", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Data Mining and Machine Learning", "DMML", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "DE-Cloud Virtualization and Big Data", "CVBD", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "DE-Advanced Graph Theory", "AGT", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "DE-Embedded system", "ES", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "PG lab II", "PG-Lab-II", 2, 2, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Institute Level Open Elective Sem6", "ILOE-Sem6", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Massively Open Onlie Course", "MOOC", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Institute Level Open Elective Sem8", "ILOE-Sem8", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Bioinformatics", "BI", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Internet of Things", "IOT", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Applied Cyber Security", "ACS", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Web Technology", "WT", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Wireless and Mobile Security", "WMS", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Network Security", "NS", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Advanced Database and Information Retrieval", "ADIR", 1, 3, FALSE, 1);
INSERT INTO subject(subjectName, subjectShortName, eachSlot, nSlots, batches, snapshotId) VALUES ( "Cloud Computing and Security", "CCS", 1, 3, FALSE, 1);
