USE timeTable;
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-S1", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-S1"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-S2", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-S2"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-S3", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-S3"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-S4", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-S4"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-S1", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-S1"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-S2", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-S2"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-S3", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-S3"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-S4", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-S4"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-DSY", 15, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-DSY"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-DSY", 15, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-DSY"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
