USE timeTable;
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D1"),(SELECT classId from class WHERE classShortName="FYBT1"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D2"),(SELECT classId from class WHERE classShortName="FYBT2"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D3"),(SELECT classId from class WHERE classShortName="FYBT3"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D4"),(SELECT classId from class WHERE classShortName="FYBT4"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-A5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-A5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-B5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-B5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-C5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-C5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYBT-D5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYBT-D5"),(SELECT classId from class WHERE classShortName="FYBT5"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-C-S1", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-C-S1"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-C-S2", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-C-S2"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-C-S3", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-C-S3"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-C-S4", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-C-S4"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-C-DSY", 15, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-C-DSY"),(SELECT classId from class WHERE classShortName="SYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-I-S1", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-I-S1"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-I-S2", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-I-S2"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-I-S3", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-I-S3"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-I-S4", 22, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-I-S4"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SY-I-DSY", 15, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SY-I-DSY"),(SELECT classId from class WHERE classShortName="SYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-T1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-T1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-T2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-T2"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-T3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-T3"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-T4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-T4"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-T5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-T5"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-T1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-T1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-T2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-T2"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-T3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-T3"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-T4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-T4"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-T5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-T5"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYMT-CE1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYMT-CE1"),(SELECT classId from class WHERE classShortName="FYMT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("FYMT-IS1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="FYMT-IS1"),(SELECT classId from class WHERE classShortName="FYMT-IS"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("SYMT-CE1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="SYMT-CE1"),(SELECT classId from class WHERE classShortName="SYMT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-CSFLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-CSFLP1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-CSFLP2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-CSFLP2"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-EC1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-EC1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-EC2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-EC2"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-NLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-NLP1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-WST1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-WST1"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-WST2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-WST2"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-WST3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-WST3"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-WST4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-WST4"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-WST5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-WST5"),(SELECT classId from class WHERE classShortName="BT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-CSFLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-CSFLP1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-CSFLP2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-CSFLP2"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-EC1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-EC1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-EC2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-EC2"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-NLP1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-NLP1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-WST1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-WST1"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-WST2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-WST2"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-WST3", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-WST3"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-WST4", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-WST4"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-WST5", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-WST5"),(SELECT classId from class WHERE classShortName="BT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-FOSS1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-FOSS1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-CBD1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-CBD1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-CG1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-CG1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-CPES1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-CPES1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("C-DM1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="C-DM1"),(SELECT classId from class WHERE classShortName="TYBT-CE"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-CBD1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-CBD1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-CBD2", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-CBD2"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-CG1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-CG1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-CPES1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-CPES1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-DM1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-DM1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
INSERT INTO batch(batchName, batchCount, snapshotId) VALUES ("I-FOSS1", 20, 1);
INSERT INTO batchClass(batchId, classId, snapshotId) VALUES ((SELECT batchId FROM batch WHERE batchName="I-FOSS1"),(SELECT classId from class WHERE classShortName="TYBT-IT"), 1);
