USE timeTable;
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "S.Y. B.Tech. Computer Engineering", "SYBT-CE", 4, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "S.Y. B.Tech. Information Technology", "SYBT-IT", 4, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "T.Y. B.Tech. Computer Engineering", "TYBT-CE", 6, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "T.Y. B.Tech. Information Technology", "TYBT-IT", 6, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "B.Tech. Computer Engineering", "BT-CE", 8, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "B.Tech. Information Technology", "BT-IT", 8, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "First Year B.Tech. Div 1", "FYBT1", 2, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "First Year B.Tech. Div 2", "FYBT2", 2, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "First Year B.Tech. Div 3", "FYBT3", 2, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "First Year B.Tech. Div 4", "FYBT4", 2, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "First Year B.Tech. Div 5", "FYBT5", 2, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "F.Y. M.Tech. Computer Engineering", "FYMT-CE", 2, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "F.Y. M.Tech. Information Security", "FYMT-IS", 2, 80, 1);
INSERT INTO class(className, classShortName, semester, classCount, snapshotId) VALUES ( "S.Y. M.Tech. Computer Engineering", "SYMT-CE", 2, 80, 1);
