USE timeTable;
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "NONE", "NONE", 0, 0);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "S.Y. B.Tech. Computer Engineering", "SYBT-CE", 4, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "S.Y. B.Tech. Information Technology", "SYBT-IT", 4, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "T.Y. B.Tech. Computer Engineering", "TYBT-CE", 6, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "T.Y. B.Tech. Information Technology", "TYBT-IT", 6, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "B.Tech. Computer Engineering", "BT-CE", 8, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "B.Tech. Information Technology", "BT-IT", 8, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "First Year B.Tech.", "FYBT", 2, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "F.Y. M.Tech. Computer Engineering", "FYMT-CE", 2, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "F.Y. M.Tech. Information Security", "FYMT-IS", 2, 80);
INSERT INTO class(className, classShortName, semester, classCount) VALUES ( "S.Y. M.Tech. Computer Engineering", "SYMT-CE", 2, 80);
