USE timeTable;
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "AC 202", "AC 101", 100);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "AC 203", "AC 102", 100);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "AC 204", "AC 103", 100);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "SH ENTC EXTN", "SH", 80);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "DBMS Lab", "DBMSL", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "FOSS Lab-1", "FOSS1", 25 );
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "FOSS Lab-2", "FOSS2", 25 );
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Linux Lab", "LL", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Graphics and Multimedia Lab", "GML", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Digital Systems Lab", "DSL", 15);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Programming Lab", "PL", 21);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "System Software Lab", "SSL", 24);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Advanced Software Lab", "ASL", 21);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Information Security Lab", "ISL", 22);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Cognizant Lab-1", "Cogni-1", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Cognizant Lab-2", "Cogni-2", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Cognizant Lab-3", "Cogni-3", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Cognizant Lab-4", "Cogni-4", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Cognizant Lab-5", "Cogni-5", 20);
INSERT INTO room(roomName, roomShortName, roomCount) VALUES ( "Data Mining Lab", "DML", 15);
