USE timeTable;
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Dr. Jibi Abraham", "Jibi", 12, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. Abhijit A.M.", "Abhijit", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Dr. Jagannath Aghav", "Aghav", 12, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Dr. V. Z. Attar", "Vahida", 10, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. S. K. Gaikwad", "Gaikwad", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Ms. S. N. Ghosh", "Soma", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. S. N. Ghotkar", "Ghotkar", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Dr. S. U. Ghumbre", "Ghumbre", 10, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. S. P. Gosavi", "Gosavi", 14, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Dr. Y. V. Haribhakta", "Haribhakta", 14, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Dr. V. S. Inamdar", "Vandana", 10, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. A. D. Joshi", "Joshi", 0, 0, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. V. M. Khadse", "Khadse", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. V. K. Khatavkar", "Vaibhav", 10, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. D. D. Kshirsagar", "Kshirsagar", 0, 0, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. S. S. Kumbhar", "Kumbhar", 10, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. S. B. Mane", "Mane", 14, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Dr. V. K. Pachghare", "Pachghare", 14, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Ms. A. B. Patil", "Archana", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Ms. T. R. Pattanshetti", "Tanuja", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. S. T. Sawant", "Suraj", 0, 0, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Ms. V. V. Kamble", "Vibhavari", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Ms. A. Biswas", "Aparna", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. A. A. Sawant", "Sawant", 6, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Uma Gajendragadkar", "Uma", 3, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Ms. Rajni Moona", "Rajani", 15, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. S. P. Dixit", "Dixit", 3, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. Jignesh Mangukiya", "Jignesh", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. Rahul B. Adhav", "Rahul", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Mr. Nishchay Mhatre", "Nishchay", 3, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Gauri", "Gauri", 3, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Jadgish Kamble", "Jagdish", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Nikita Mahajan", "Nikita", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Madhuri Aher", "Madhuri", 0, 0, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Sheetal Rathod", "Sheetal", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Kulkarni Snehal", "Snehal", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Asmita Manna", "Asmita", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Rohini Sarode", "Rohini", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Maths Teacher1", "Maths1", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Applied Science Teacher1", "Appsci1", 16, 24, 1);
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Institute Faculty 1", "Insti1", 16, 24, 1 );
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Institute Faculty 2", "Insti2", 16, 24, 1 );
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Institute Faculty 3", "Insti3", 16, 24, 1 );
INSERT INTO teacher(teacherName, teacherShortName, minHrs, maxHrs, deptId) VALUES ( "Institute Faculty 4", "Insti4", 16, 24, 1 );
